language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
gemfile:
  - Gemfile32
  - Gemfile
  - Gemfile.rails41
services:
  - memcache
  - mysql
before_script:
  - mysql -e 'create database identity_cache_test'
